sinapsis_web/apps_sinapsis/books/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import BooksListView,BookDetailView ,BookCrearView,BookDeleteView,BookUpdateView


app_name = "books"

urlpatterns = [
    path("", BooksListView.as_view(), name="all"),
    path("<int:pk>/detail/",BookDetailView.as_view(), name="detail"),
    path("crear/",BookCrearView.as_view(), name="crear"),
    path("<int:pk>/update/",BookUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/",BookDeleteView.as_view(), name="delete"),
] 

sinapsis_web/apps_sinapsis/reviews/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import ReviewListView, ReviewQueriesList , ReviewCreateView

app_name = "reviews"

urlpatterns = [
    path("", ReviewListView.as_view(), name="all"),
    path("search",ReviewQueriesList.as_view(),name='searcher'),
    path("create/",ReviewCreateView.as_view(),name='create'),
]

sinapsis_web/sinapsis_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path("", include("apps_sinapsis.login_app.urls")),
    path("admin/", admin.site.urls),
    path("blog/",include("apps_sinapsis.reviews.urls")),
    path("books/",include("apps_sinapsis.books.urls")),
    path("contact/", include("apps_sinapsis.books.store_urls")),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

sinapsis_web/templates/base_proyecto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{{ title }}</title>
</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</html>

sinapsis_web/templates/sinapsis_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './css/main_books/main_style.css'%}">
    <title>SINAPSIS {{ request.path|slice:"1:"|slice:":-1"|upper }}</title>
</head>

<body>
    <header>
        <div class="logo">
            <h1>
                <a href="{% url 'landing_page' %}">SINAPSIS BLOG STORE</a>

            </h1>
        </div>

        <div class="nav">
            <ul>
                {% url 'reviews:all' as url %}
                <li class="{% if request.path == url %}active{% endif %}">
                    <a href="{{url}}">BLOG</a>
                </li>

                {% url 'books:all' as url %}
                <li class="{% if request.path == url %}active{% endif %}">
                    <a href="{{ url }}">BOOKS</a>
                </li>
                {% url 'stores:all' as url %}
                <li class="{% if request.path == url %}active{% endif %}"><a href="{{ url }}">CONTACT</a></li>

                {% url 'reviews:create' as url %}
                <li class="{% if request.path == url %}active{% endif %}"><a href="{{ url }}">CREAR REVIEW</a></li>

            </ul>
        </div>
    </header>
    <main>
        <div>
            {% if user.nombre %}
            <h3>Bienvenido! {{ user }}</h3>
            <button class="extra">
                <a href="{% url 'logout' %}">Logout</a>
            </button>

            {% else %}
            <h3>Bienvenido! </h3>
            {% endif %}
        </div>

        {% block content%}
        {% endblock %}
    </main>
</body>

</html>