sinapsis_web/apps_sinapsis/books/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import BooksListView,BookDetailView ,BookCrearView,BookDeleteView,BookUpdateView


app_name = "books"

urlpatterns = [
    path("", BooksListView.as_view(), name="all"),
    path("<int:pk>/detail/",BookDetailView.as_view(), name="detail"),
    path("crear/",BookCrearView.as_view(), name="crear"),
    path("<int:pk>/update/",BookUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/",BookDeleteView.as_view(), name="delete"),
] 

sinapsis_web/sinapsis_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path("", include("apps_sinapsis.login_app.urls")),
    path("admin/", admin.site.urls),
    path("blog/",include("apps_sinapsis.reviews.urls")),
    path("books/",include("apps_sinapsis.books.urls")),
    path("contact/", include("apps_sinapsis.books.store_urls")),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

sinapsis_web/apps_sinapsis/books/models.py
from django.db import models
from django.db.models.query import QuerySet

from apps_sinapsis.utils.Money import MONEY

from apps_sinapsis.utils.validate_functions import validate_ISBN
from django.utils.translation import gettext_lazy as _


class GENERO(models.Model):
    genero = models.CharField(max_length=154,unique=True,blank=False,null=False)

    def __str__(self) -> str:
        return f"{self.genero}"
    

class StoreManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().exclude(status=False)


class Store(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=245, default='Tienda-Online')
    status = models.BooleanField(default=True)
    provincia = models.CharField(max_length=100,default="Buenos Aires")
    location_src = models.TextField(
        default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3285.830022710853!2d-58.68286492323899!3d-34.55785885507963!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcbc45fa07e48f%3A0x2ede182f3817f97e!2sLa%20Plata%20889%2C%20B1661HYL%20Bella%20Vista%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1sen!2sar!4v1687761473818!5m2!1sen!2sar"
    )
    horarios = models.CharField(max_length=100, default= "Lunes a Viernes de 9am a 18pm")

    
    objets_all = models.Manager()
    objects = StoreManager()
    
    def __str__(self) -> str:
        return f"{self.name}"

class Book(models.Model):

    nombre =  models.CharField(max_length=100)
    isbn =  models.CharField( 
        max_length=17,
        validators=[validate_ISBN],
        default="978-3-16-148410-0"
    
    )
    release_date = models.DateField(_("Date"), auto_now_add=True)
    genero  = models.ManyToManyField(GENERO)
    author = models.CharField(max_length=100)
    paginas = models.IntegerField(default=100, null=False , blank=True) 
    currency = models.CharField(
        max_length = 2,
        choices = MONEY.choices,
        default = MONEY.PESOS
    )
    precio = models.DecimalField(null=False,
                                  blank=False,
                                  default=1000.00,
                                  max_digits=12,
                                  decimal_places=2)

    sinapsis = models.TextField(default="Sin sinapsis aun cargadas")
    short_sinapsis = models.TextField(default="Sinapsis corta")
    cantidad = models.IntegerField(default=10, null=False , blank=True) 
    store = models.ManyToManyField(Store)
    
    image_url = models.ImageField(
        null=True, blank=True , upload_to= "images/" ,default="images/bg_book.jpg"
    )

    def __str__(self) -> str:
        return f"Titulo:\n{self.nombre} <|> ISBN:\t{self.isbn}"

    

sinapsis_web/apps_sinapsis/books/views.py
from typing import Any, Dict
from django.shortcuts import render

from django.urls import reverse_lazy , reverse
from .models import Book , GENERO
from .models import Store

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from django.views.generic.edit import DeleteView , CreateView , UpdateView 


from apps_sinapsis.sinapsis_cliente.mixins import OwnerSinapsisMixin
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class BooksBaseView():
    template_name = 'book_list.html'
    model = Book
    fields = '__all__'
    sucess_url = reverse_lazy('books:all')
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context
    

class BooksListView(LoginRequiredMixin,BooksBaseView,ListView):
    """
    Lista de Books
    """
    
class BookDetailView(LoginRequiredMixin,BooksBaseView,DetailView):
    template_name = "blog_detail.html"
    
class BookCrearView(LoginRequiredMixin,OwnerSinapsisMixin,BooksBaseView,CreateView):
    template_name = "book_create.html"
    extra_context = {
        "tipo" : "Agregar"
    }
    
    def get_success_url(self) -> str:
        return reverse('books:all')
    
class BookUpdateView(LoginRequiredMixin,OwnerSinapsisMixin,BooksBaseView,UpdateView):
    template_name = "book_create.html"
    
    extra_context = {
        "tipo" : "Modificar"
    }
    
    def get_success_url(self) -> str:
        return reverse('books:all')
    
class BookDeleteView(LoginRequiredMixin,OwnerSinapsisMixin,BooksBaseView,DeleteView):
    
    def get_success_url(self) -> str:
        return reverse('books:all')
    
    
    
    
    

class StoreBaseView():
    template_name = 'contact_list.html'
    model = Store
    fields = '__all__'
    sucess_url = reverse_lazy('stores:all')
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context

class StoreListView(LoginRequiredMixin,StoreBaseView,ListView):
    """
    Lista de Stores
    """
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["filtered"] = Store.objects.all().values()
        return context
    
    
class StoreDetailView(LoginRequiredMixin,StoreBaseView,DetailView):
    template_name = "contact_detail.html"
    
    
class StoreCreateView(LoginRequiredMixin,OwnerSinapsisMixin,StoreBaseView,CreateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo" : "Agregar"
    }
    
    def get_success_url(self) -> str:
        return reverse('stores:all')
    
    
    
class StoreUpdateView(LoginRequiredMixin,OwnerSinapsisMixin,StoreBaseView,UpdateView):
    template_name = "store_create.html"
    extra_context = {
        "tipo" : "Modificar"
    }
    
    def get_success_url(self) -> str:
        return reverse('stores:all')
    
class StoreDeleteView(LoginRequiredMixin,OwnerSinapsisMixin,StoreBaseView,DeleteView):    
    def get_success_url(self) -> str:
        return reverse('stores:all')

sinapsis_web/apps_sinapsis/books/templates/blog_detail.html
{% extends 'sinapsis_base.html' %}

{% block content %}
<div class="book-detail">
    <div class="book-options">
        {% if book.image_url %}
        <img src="{{ book.image_url.url }}" alt="{{book.isbn}}" class="book-img">
        {% else %}
        <img src="/media/images/bg_book.jpg" alt="{{book.isbn}}" class="book-img">
        {% endif %}

        <div class="edition-option-book">
            <button class="update">
                <a href="{% url 'books:update' book.id %}">Modificar</a>
            </button>

            <form method="post" action="{% url 'books:delete' book.id%}">
                {% csrf_token %}
                <button type="submit" class="delete"> Borrar </button>
            </form>
        </div>
    </div>
    <div>
        <h1>Nombre del Libro : {{book.nombre}}</h1>
        <h3>ISBN : {{ book.isbn }}</h3>
        <p> El libro contiene {{book.paginas}} páginas</p>
        <p>{% if book.currency == 'PS'%}
            Pesos Argentinos
            {% elif book.currency == 'EU' %}
            Euros
            {%else%}
            Dolares
            {% endif %}
            {{book.precio}}</p>

        <p>{{book.release_date}}</p>
        <p>Unidades Disponibles : {{book.cantidad}}</p>
        <hr>
        <h3>
            Tiendas disponibles
        </h3>
        <div class="store-container">
            {% for store in book.store.all%}
            <span class="store pick-choice">
                <a href="{% url 'stores:detail' store.id %}">{{store}}</a>
            </span>

            {% endfor%}
        </div>

        <div class="genero">
            Generos asociados al libro:
            {% for genero in book.genero.all%}
            <p class="pick-choice">
                {{ genero | capfirst }}
            </p>
            {% endfor %}
        </div>
        <hr>
        <p>
            Sinapsis : {{book.sinapsis}}
        </p>
    </div>
</div>

{% endblock %}

sinapsis_web/apps_sinapsis/books/templates/book_create.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="book-creator">
    <form method=POST enctype="multipart/form-data">
        <h1> Agregar un libro</h1>
        {% csrf_token %}
        <div class="formulario">{{form.as_p}}</div>
        <input type="submit" class="extra" value="{{ tipo }}" />
    </form>
    <a href="{% url 'books:all' %}"> Books </a>
</div>
{% endblock %}

sinapsis_web/apps_sinapsis/books/templates/book_list.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="book-container">
    <h1><a href="{% url 'books:crear' %}"> Agregar Book</a></h1>
    {% for book in book_list%}
    <div class="container">


        <p class="nombre">
            <a href="{% url 'books:detail' book.id %}" class="name-id">

                {{ book.nombre | capfirst }}
            </a>
        </p>

        <p class="sinapsis">Sinapsis:
            {{book.short_sinapsis}}
        </p>
        <p>{% if book.currency == 'PS'%}
            Pesos Argentinos
            {% elif book.currency == 'EU' %}
            Euros
            {%else%}
            Dolares
            {% endif %}
            {{book.precio}}</p>


        <h3>Tiendas</h3>
        <div class="wrapper">
            {% for store in book.store.all%}
            <span class="store">
                {{store}}
            </span>

            {% endfor%}
        </div>

        <div class="genero">
            {% for genero in book.genero.all%}
            <p class="pick-choice">
                {{ genero | capfirst }}
            </p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

sinapsis_web/apps_sinapsis/books/templates/contact_detail.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="container-store-location">
    <h1>Nombre de la tienda: {{store.name}}</h1>
    <p>Lugar: {{store.location}}</p>

    {% if store.status == True %}
    <h3>La tienda está disponible!</h3>
    <p>Horarios de atencion</p>
    <p>{{store.horarios}}</p>
    {% else %}
    <h3>La tienda no se encuentra disponible!</h3>

    {% endif %}


    <iframe src="{{store.location_src}}" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>
{% endblock %}

sinapsis_web/apps_sinapsis/books/templates/contact_list.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div>
    <h1>
        <a href="{% url 'stores:crear' %}"> Agregar una tienda </a>
    </h1>
</div>
<div class="store-container">

    {% for store in filtered %}

    <div class="store-wrapper">
        <h1>{{store.name}}</h1>
        <p>{{store.location}}</p>
        <p>{{store.provincia}}</p>

        <div class="edition-option">
            <button class="update">
                <a href="{% url 'stores:update' store.id %}">Modificar</a>
            </button>

            <form method="post" action="{% url 'stores:borrar' store.id%}">
                {% csrf_token %}
                <button type="submit" class="delete"> Borrar </button>
            </form>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock %}

sinapsis_web/apps_sinapsis/books/templates/store_create.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="store-creator">
    <form method=POST>
        <h1> Agregar una tienda</h1>
        {% csrf_token %}
        <div class="formulario">{{form.as_p}}</div>
        <input type="submit" class="extra" value="{{ tipo }}" />
    </form>
    <a href="{% url 'stores:all' %}"> Stores </a>
</div>
{% endblock %}