sinapsis_web/apps_sinapsis/reviews/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import ReviewListView, ReviewQueriesList , ReviewCreateView

app_name = "reviews"

urlpatterns = [
    path("", ReviewListView.as_view(), name="all"),
    path("search",ReviewQueriesList.as_view(),name='searcher'),
    path("create/",ReviewCreateView.as_view(),name='create'),
]

sinapsis_web/sinapsis_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path("", include("apps_sinapsis.login_app.urls")),
    path("admin/", admin.site.urls),
    path("blog/",include("apps_sinapsis.reviews.urls")),
    path("books/",include("apps_sinapsis.books.urls")),
    path("contact/", include("apps_sinapsis.books.store_urls")),
]

urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

sinapsis_web/apps_sinapsis/reviews/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime

# Create your models here.

class Review(models.Model):
    usuario = models.CharField(max_length=255,default='No user',blank=True,null=False)
    
    book = models.ForeignKey(
        'books.Book',
        on_delete = models.CASCADE
    )
    review_text = models.TextField(default='No review yet')
    stars = models.IntegerField(default=1, validators=[MaxValueValidator(10),MinValueValidator(1)])
    date_review = models.DateTimeField(default=datetime.now, blank=False , null=False)
    def __str__(self) -> str:
        return f"{self.review_text}"
    

sinapsis_web/apps_sinapsis/reviews/forms.py
from django.forms import ModelForm

from .models import Review

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

sinapsis_web/apps_sinapsis/reviews/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView

from django.views.generic.edit import CreateView

from .models import Review
from apps_sinapsis.books.models import Book
from apps_sinapsis.sinapsis_cliente.mixins import OwnerSinapsisMixin
from django.contrib.auth.mixins import LoginRequiredMixin


from django.db.models import Q

from .forms import ReviewForm

# Create your views here.


class ReviewBaseList():
    template_name = "review.html"
    model = Review
    fields = '__all__'
    success_url = reverse_lazy('reviews:all')
    
class ReviewListView(ReviewBaseList,ListView):
    """
    List of reviews
    """
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context =  super().get_context_data(**kwargs)   
        return context
    
class ReviewQueriesList(ReviewBaseList,ListView):
    
    success_url = reverse_lazy('reviews:searcher')
    
    def get_context_data(self,**kwargs: Any) -> Dict[str, Any]:
        search_review = self.request.GET.get("search")
        context = super().get_context_data(**kwargs)
        context["filtered"] = Review.objects.filter(Q(book__nombre__icontains=search_review))
        return context
    
    
class ReviewCreateView(LoginRequiredMixin,OwnerSinapsisMixin,CreateView):
    
    template_name = "review_create.html"
    form_class = ReviewForm
    success_url = reverse_lazy('reviews:all')
    
    def form_valid(self,form):
        form.save()
        return super().form_valid(form)

sinapsis_web/apps_sinapsis/reviews/templates/review.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="review-container">
    <div>
        {% if filtered %}
        {% for review in filtered %}
        <div>
            <h2>
                Recomendado por: {{review.usuario}}
            </h2>
            <h3>{{review.book.nombre}}</h3>
            <div>
                <label for="">Stars</label>
                <input type="range" min="1" max="10" value="{{review.stars}}" disabled readonly>
                <span>{{review.stars}}</span>
            </div>
            <p>
                {{review.review_text}}
            </p>
            <p>
                Fecha de la review : {{review.date_review}}
            </p>
            <hr>
        </div>
        {% endfor %}
        {% else%}
        {% for review in review_list %}
        <div>
            <h2>
                Recomendado por: {{review.usuario}}
            </h2>
            <h3>{{review.book.nombre}}</h3>
            <div>
                <label for="">Stars </label>
                <input type="range" min="1" max="10" value="{{review.stars}}" disabled readonly>
                <span>{{review.stars}}</span>
            </div>
            <p>
                {{review}}
            </p>
            <p>
                Fecha de la review : {{review.date_review}}
            </p>
            <hr>
        </div>
        {% endfor %}

        {% endif %}
    </div>
    <div>
        {% if review_list %}
        <h1> Busqueda por libro</h1>
        <form action="{% url 'reviews:searcher' %}" method=GET>

            <input type="text" name="search">
            <button type="submit">Buscar</button>
        </form>
        {% else %}
        <h1> No hay reviews aún</h1>
        {% endif %}
    </div>
</div>

{% endblock %}

sinapsis_web/apps_sinapsis/reviews/templates/review_create.html
{% extends 'sinapsis_base.html' %}

{% block content %}

<div class="review-creator">
    <form method=POST action="{% url 'reviews:create' %}">
        <h1> CREATE A REVIEW</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="extra"> Crear</button>
    </form>
    <a href="{% url 'reviews:all' %}"> Reviews </a>
</div>

{% endblock %}